### ISSUE TITLE
Source zip file doesn't include quixe directory contents

### ISSUE THREAD

**Issue by rubereaglenest** [erkyrath/lectrote#101]
In the releases page, the source code in zip, has no contents for the quixe directory, so the build fails with error. I've downloaded the last version of quixe and dropped the files there and now the build continues normally in that point (it fails later, but that is another story).

**Comment by erkyrath** [comment]
That's correct. Quixe is supposed to be installed by the "preinstall" step of the npm install.

I wrote that step in a hacky way which presupposes both bash and git being available, but that's a separate problem. Sorry...

**Comment by rubereaglenest** [comment]
Ah, that's because I jumped directly to the Package a game instructions, maybe it could worth to add the step "npm install" if you didn't do it before.
