### ISSUE TITLE
Include licenses for all VMs

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/lectrote#102]
To fulfil all righteousness we really should be including all the licenses for the VMs/other dependencies. A simple static HTML page should be easy enough to add to the app.

**Comment by erkyrath** [comment]
I've added into to the LICENSE file and README.md. Does that cover it?

**Comment by curiousdannii** [comment]
I think the individual emglken terps need their own licenses listed, especially Hugo as it's BSD-2-Clause not MIT.

It probably also needs to be visible somewhere in the app itself.

**Comment by erkyrath** [comment]
I added licenses for Git and Hugo. I think that's all. (The emglken repository doesn't have any obvious list of licenses...)

I also added a link in the About menu. I'm not terribly worried about the difference between included and web-linked information.

**Comment by curiousdannii** [comment]
> The emglken repository doesn't have any obvious list of licenses...

Yeah, that's on my todo list.
