### ISSUE TITLE
In MacOS, the app asks for permission to access photos and contacts

### ISSUE THREAD

**Issue by WanderingCow** [erkyrath/lectrote#112]
I can't think of a reason why it would need access to either of those?

**Comment by erkyrath** [comment]
This must be built into the Electron framework. I haven't looked at how that's configured since MacOS 10.14 came out. I'll take a look next time I do a release and see if there are privacy configuration options.

**Comment by erkyrath** [comment]
I haven't seen this permission request on MacOS (and I never gave any version of Lectrote permission to access that stuff). So I think this has been fixed, either by smarter behavior of Electron or smarter behavior of MacOS.
