### ISSUE TITLE
The startup shell script does not pass arguments

### ISSUE THREAD

**Issue by cspiegel** [erkyrath/lectrote#117]
The Linux release of Lectrote has a wrapper script `/usr/bin/lectrote` which just calls out to `/opt/lectrote/Lectrote`.  However, this script does not pass arguments to `/opt/lectrote/Lectrote` so you cannot call it as:

```
lectrote zork1.z3
```

Since `/opt/lectrote/Lectrote` does accept arguments, this wrapper ought to pass them along, i.e. instead of

```
exec "/opt/lectrote/Lectrote"
```
the script should be

```
exec "/opt/lectrote/Lectrote" "$@"
```

**Comment by erkyrath** [comment]
Any idea where this Linux release is set up or packaged?

**Comment by cspiegel** [comment]
This is just the 64-bit Linux version from the releases page here.  I looked through the source and didn't see anything generating the shell script, so I have to assume it's part of Electron, i.e. I'm guessing that there's some sort of Electron packaging step which automatically creates this script (I've never used Electron other than as an end-user).  Unless someone knows offhand about Electron packaging on Linux, I can look into it and see if there's something to easily tune the package generation output.

**Comment by erkyrath** [comment]
That would be helpful. I'm actually kind of confused; when I unzip the file (Lectrote-1.3.3-linux-x64.zip) I don't see a "lectrote" shell script, and I'm not sure how one would get into /usr/bin.

**Comment by cspiegel** [comment]
Time for an embarrassing admission: it appears that I wrote my own `/usr/bin/lectrote` script long ago and completely forgot that it wasn't part of the package when I upgraded to 1.3.3.  So not only was I wrong about it coming with Lectrote, I also wrote it incorrectly in the first place.  Apologies for the noise here!

**Comment by erkyrath** [comment]
Heh, no problem.
