### ISSUE TITLE
Counterfeit Monkey only starts with Quixe

### ISSUE THREAD

**Issue by angstsmurf** [erkyrath/lectrote#122]
We have discussed this on the Intfiction.org forum, but I figured it wouldn't hurt to have an issue here as well, so that we don't forget.

The relevant posts are https://intfiction.org/t/lectrote-1-3-6/46539/12 and https://intfiction.org/t/suppressing-line-break-after-cancelling-line-event/13488/8 at the time of writing.

> Under Lectrote-Glulxe it crashes saying “OOM” (abortOnCannotGrowMemory). Under Lectrote-Git it just doesn’t start up – no error message, which is odd, but leaves me no strings to pull.

> In Lectrote 1.3.3, it is possible to get to the initial question (“Can you hear me?”) in Lectrote-Git by compiling Counterfeit Monkey without Startup Precomputation support. However, it is not possible to actually enter an answer, as pressing the enter key has no effect. In 1.3.4 and later, it won’t even start.

It is a little cumbersome to remove Startup Precomptuation from Counterfeit Monkey, so I've uploaded a binary without it here: https://github.com/i7/counterfeit-monkey/releases/tag/r9b7

**Comment by erkyrath** [comment]
Dannii has reworked the emglken interpreters; this should work in the next release.

**Comment by angstsmurf** [comment]
I tested the current code, and standard builds now work, as does debug builds without Startup Precomputation. Debug builds with Startup Precomputation still hang at start with an eternal spinning compass in both Git and Glulxe, but work with Quixe.

**Comment by angstsmurf** [comment]
I did some further testing, now that debug builds kind-of run. TEST ACT1 works, but both non-Quixe interpreters seem to hang on TEST ACT2.  When they "get stuck" the console always shows the same kind of errors, both when they refuse to start at all and when stuck on Act 2:

```
file_fopen: failed to open : Error: ENOENT: no such file or directory, open
~/lectrote-master/quixe/lib/elkote.min.js:207

TypeError: Cannot read property 'fseek' of null
~/lectrote-master/emglken/glulxe.js:1

Not sending repeated generation number: 0
~/lectrote-master/quixe/lib/elkote.min.js:207
```

The second one will of course show `git.js:1`on Git.
The last one will sometimes be absent, sometimes repeat with different numbers.

**Comment by curiousdannii** [comment]
Hmm, I'll look into it.

**Comment by angstsmurf** [comment]
I wonder if it has something to do with reading or writing external files. A new standard build will hang in Lectrote-Glulxe when trying to start, with the same errors in console. But release 9, which has a startup state in the Blorb, will start without errors.

**Comment by curiousdannii** [comment]
Yeah it's definitely the external files, which is the tricky part of Emglken, because of how I've implemented the virtual file system. It shouldn't be displaying an error, I thought that was caught and dealt with.

Btw, if you have extra time and like testing things, you can also see how it goes with the [emglken script from the npm package](https://www.npmjs.com/package/emglken). Though it will probably be a lot of the same thing.

**Comment by curiousdannii** [comment]
Seems like the bug was another one of those annoying dumb ones caused by a dumb typo. Which I fixed yesterday! If you can try the code from my PR @angstsmurf let me know if you have any more troubles.

**Comment by angstsmurf** [comment]
I'll [just link to my comment on the PR](https://github.com/erkyrath/lectrote/pull/125#issuecomment-682588164) here.
