### ISSUE TITLE
NVDA reads the whole screen when it is updated

### ISSUE THREAD

**Issue by sukiletxe** [erkyrath/lectrote#127]
I am using Lectrote v1.3.7, and NVDA reads the whole screen when it is updated. So, for example, if I type "i" then press enter, the whole screen is read instead of just, for example "> i You're carrying nothing".

This may be fixable by updating Elektron. Latest Google Chrome (Browser) version 85.0.4183.121 works fine in the web version of Quixe.

I can confirm that latest versions of Elektron up to and including v9 do not work as expected. I cannot test with v10 as Lectrote fails with it to load games (my update procedure has been just editing package.json by hand).

**Comment by erkyrath** [comment]
Thanks for the note.

I've been updating Lectrote by one major version at a time, since, as you see, there are usually minor deprecation issues to clean up. I'll take a look at 9 and 10 soon.

**Comment by sukiletxe** [comment]
Thanks, feel free to ping me if you need testing.

**Comment by erkyrath** [comment]
1.3.8 with Electron 9 is out. I'm going to give it a little more soak time before I bump to 10.

However, I updated some of the API calls. It may run on 10 now if you edit the package.json.

**Comment by sukiletxe** [comment]
Fixed with Elektron 10. Now only the last part of the screen (after, and not including the line of the typed command) is read. Only problem is that if no command is typed (think of some cutscenes where text is added in chunks) no text is reported. Same happens in hints. But well, this also is the case in Chrome.

Closing, thanks very much for updating!
