### ISSUE TITLE
Random numbers 

### ISSUE THREAD

**Issue by leugengroot** [erkyrath/lectrote#130]
When I use the [random-number extension from Roger Firth](http://www.ifarchive.org/if-archive/infocom/compilers/inform6/library/contributions/random.h) (or the standard-library function and create a new seed), I always get the same random-numbers when I restart Lectrote. 

When I run the same z-file with other interpreters (Yazim, Gargoyle) I get different numbers every time I restart the application.

Tested with Lectrote 1.3.12 (macOS) and Inform 6.34
[random_test.zip](https://github.com/erkyrath/lectrote/files/5939320/random_test.zip)

Attached test-file includes such a z-file as the source code as well.

**Comment by erkyrath** [comment]
This is an interpreter issue: https://github.com/curiousdannii/ifvms.js

**Comment by curiousdannii** [comment]
I'm pretty sure this is just the autosave feature. If you restart or quit and reload you'll get new numbers.
