### ISSUE TITLE
[Windows] Can't open two Lectrote instances

### ISSUE THREAD

**Issue by tobiasvl** [erkyrath/lectrote#131]
If Lectrote is running and I try to launch another instance of it, I just get the following error message:

![image](https://user-images.githubusercontent.com/80824/108610873-7dc39800-73d9-11eb-8c0a-a588b734aeea.png)

At first I thought it was because Lectrote was trying to load the same game file as I had loaded in the first instance (but it was locked or something), but it happens even if the first instance is on the splash screen with no game file loaded.

**Comment by erkyrath** [comment]
I've checked in a change that should prevent this. (The argument list now ignores any argument that starts with a dash.)
