### ISSUE TITLE
Counterfeit Monkey does not let me see save files

### ISSUE THREAD

**Issue by estelendur** [erkyrath/lectrote#137]
I am using Lectrote 1.4.0 on Ubuntu 18.04.6. I downloaded the linux zip and ran from terminal. I'm playing CounterfeitMonkey-10.gblorb. When I save, it creates a save file. When I try to restore, the file picker won't let me see the save file.

Save file in context in the Lectrote-linux-x64 directory:
![save-file-in-context](https://user-images.githubusercontent.com/10409866/135192958-cdcc9a52-2d49-4f22-937a-47e471ad2052.png)

Save file properties:
![save-file-properties](https://user-images.githubusercontent.com/10409866/135192967-fc2a6f2b-0871-4dfe-a1d1-4e24ecde1408.png)

File picker for restore only allowing me to see filetype "Glk Save File," of which there are none (the dropdown has zero other options but idk if I can screenshot that):
![save-file-not-there](https://user-images.githubusercontent.com/10409866/135192974-0dd60478-9526-40dc-9b95-aad2eee88991.png)

**Comment by erkyrath** [comment]
I don't have a way to test GUI apps on Linux, I'm afraid.

The file extension for save files should be `.glksave`. It looks like it's not adding that? I'm not sure why; there's no difference between the Windows and Linux save dialogue that I know of.

**Comment by estelendur** [comment]
Alright, thanks! Honestly part of the reason I made the issue was I couldn't figure out what the right save file extension was, and indeed, putting the correct one has solved the issue.
