### ISSUE TITLE
Ability to load .sav Files

### ISSUE THREAD

**Issue by Schnubbirunkel** [erkyrath/lectrote#145]
Sadly, there is a file format restriction in Lectrote, that can't be disabled. Windows Git, Gargoyle, Spatterlight and others seem to not care about the save game format. Is it possible to disable the format restriction? The .glksave files and the .sav files seem to be the same thing, but I just can't use them with Lectrote and I don't want to rename them everytime, I switch from my Ipad to my PC.

**Comment by erkyrath** [comment]
I don't think this will cause any problems. I will add that option.

This will only affect the load-game dialog. New saved games will still have the .glksave extension.
