### ISSUE TITLE
Adrift 4 games are selectable but the game never loads

### ISSUE THREAD

**Issue by kpeamon** [erkyrath/lectrote#154]
**Lectrote V1.4.4:** Adrift 4 games with extension .taf can be selected but never loads. The symbol just keeps rotating and never finish. If you want Lectrote to load Adrift 4 games you also need to add " , Adrift 4" to the start screen of Lectrote which only mentions "Select [Open Game](javascript:opengame()) to begin playing a Glulx, Z-code, Hugo, TADS, or Ink game file!"

**Comment by erkyrath** [comment]
Fixed.
