### ISSUE TITLE
Put a launcher script in bin

### ISSUE THREAD

**Issue by erkyrath** [erkyrath/lectrote#20]
Might as well be Node about this, even though most people will only use the packaged apps.

**Comment by erkyrath** [comment]
https://docs.npmjs.com/files/package.json#bin

**Comment by erkyrath** [comment]
I poked at this for a while, but I don't understand enough about node's install system. It's clear how to list a bin script in the package.json, but it's not clear how to write the script so that it launches the thing.

This works from the command line (assuming you've gotten `npm start` working to begin with):

   lectrote/node_modules/.bin/electron ~/src/lectrote/main.js

**Comment by curiousdannii** [comment]
I don't think there would be any requirement that it be a js file... you should be able to put a shell script in bin.

**Comment by erkyrath** [comment]
"You should move electron to be a dependency rather than just a dev dependency."

Aha, thanks. I think this was the bit I was missing in my experiments.
