### ISSUE TITLE
Adjust icon layout for small sizes

### ISSUE THREAD

**Issue by erkyrath** [erkyrath/lectrote#24]
The small versions of the doc icons should drop the GLULX label and recenter the graphic.

(.icns files and also docicon-64.ico)

**Comment by curiousdannii** [comment]
For Kerkerkruip on linux I made 16 and 24 bit png icons, and then used svg for the rest. I think those are the sizes that really need smaller icons. For the icns and ico you'd just export the svg for all the other sizes.

**Comment by erkyrath** [comment]
If I really want to be pedantic about icon styles: the curl shadow should be less dark (both above and below the corner). The text labels should be a lighter weight, and dark grey rather than black.

(This is to match MacOS icon styles, but hey -- they look good.)
