### ISSUE TITLE
Make sure cli.sh works locally

### ISSUE THREAD

**Issue by erkyrath** [erkyrath/lectrote#25]
Spun off from https://github.com/erkyrath/lectrote/issues/20

Comment from dannii:
> You should be able to use the npm_config_binroot config var in cli.sh - if you're asking for npm root -g then it won't work when it's running locally, won't it?

**Comment by erkyrath** [comment]
You can't get at npm_config_binroot from a /bin/sh script.

**Comment by erkyrath** [comment]
I think it sufficies to look at `npm prefix`, and if the directory name is "lectrote", run `$PREFIX/node_modules/.bin/electron $PREFIX/main.js` instead.

Does that look completely stupid?

**Comment by curiousdannii** [comment]
Yeah that makes sense.
