### ISSUE TITLE
Quitting from prompt should do something

### ISSUE THREAD

**Issue by sedm0784** [erkyrath/lectrote#5]
Steps to Reproduce:

1. Run Lectrote, start a game.
2. Type `quit`
3. When the game asks if you want to quit. Type `y` and hit <kbd>Enter</kbd>

Observed behaviour: The flashing cursor disappears
Expected behaviour: I'm not sure, but *something* should probably happen. The window should close? Or maybe it should return to the Lectrote start page? Or maybe it should just display a message along the lines of: "Game quit. Click on File->Open to start another."

**Comment by erkyrath** [comment]
The window can't just close, because the game might display a farewell message after the quit command. The player must be able to read it.

A "game has ended" banner is appropriate, although to be really sure it will have to be translucent. (A GlkOte feature, I suppose.)

**Comment by dfabulich** [comment]
I'm a fan of just appending to the farewell message, "[Press any key to exit]" and then auto-closing the window after that.
