### ISSUE TITLE
Image displayed lo-res on high-dpi screens

### ISSUE THREAD

**Issue by angstsmurf** [erkyrath/lectrote#56]
![skarmavbild-2016-05-05-kl -14 37 08](https://cloud.githubusercontent.com/assets/5066755/15043750/c1ce6d92-12cf-11e6-8819-1debe2c91052.png)

The map in Counterfeit Monkey seems to be displayed at half resolution on my Retina Macbook in Lectrote. See attached screenshot. Zoom to the left, Lectrote to the right.

**Comment by erkyrath** [comment]
These are images drawn in an HTML `<canvas>` element. It should be possible to make the canvas use retina-level rendering, but I don't have the hardware to test so I may flail a bit.

**Comment by erkyrath** [comment]
E.g. http://www.html5rocks.com/en/tutorials/canvas/hidpi/ , https://coderwall.com/p/vmkk6a/how-to-make-the-canvas-not-look-like-crap-on-retina

**Comment by angstsmurf** [comment]
I'd be happy to help with any testing. I only have this one hi-dpi device, though.

**Comment by curiousdannii** [comment]
I've got a 1.5 scale Windows device, so I can check it works on non-2.0 scale devices too.

**Comment by erkyrath** [comment]
I'll see if I can have a test build this weekend.

**Comment by erkyrath** [comment]
Please try: http://eblong.com/zarf/glulx/quixe/quixe-retina/play-full-media.html

This is Quixe with my attempt at handling devicePixelRatio correctly. If possible, test:

- Safari, Chrome, and Firefox. (Lectrote uses Chrome but this feature should work on the web page in all browsers.)
- Resizing the browser window.
- Moving the browser window from a high-DPI monitor to a low-DPI monitor and back.

The browser console log will display extra debugging info about the current DPI, so you should be able to see if it's doing vaguely the right thing.

**Comment by angstsmurf** [comment]
Well, apart from those Quota Exceeded errors, it seems to work just as intended on Safari and Firefox at least.

### created canvas with scale 2 (device 2 / backstore 1) (Firefox)
### created canvas with scale 2 (device 2 / backstore 1) (glkote.js, line 1506) (Safari)
### created canvas with scale 2 (device 2 / backstore 1) (Chrome)

Nice work!

**Comment by curiousdannii** [comment]
Looks good to me. I get the Quota Exceeded errors as well.

> The browser console log will display extra debugging info about the current DPI

Do you mean the initial DPI? I only got one of those debug messages.

**Comment by angstsmurf** [comment]
`[Log] GiLoad: trying pre-loaded load (base64)... (glkote.js, line 1506)
[Log] ### created canvas with scale 2 (device 2 / backstore 1) (glkote.js, line 1506)
[Log] ### done executing; path time = 5566 ms (quixe.js, line 179)
[Log] ### done executing; path time = 77 ms (quixe.js, line 179)
[Log] ### done executing; path time = 13 ms (quixe.js, line 179)`

Switching monitors won't work on Safari (OS X), variation on the last line when resizing, nothing when changing monitor. Changing from high-DPI to standard gives a half-size image in the same-size window that remains when moving back to high-DPI screen. Start the game on standard-DIP and it remains so when moving window to high-DPI.

Monitor switch works on Firefox and Chrome, however.

Chrome when moving back and forth:
```
glkote.js:1506 GiLoad: trying pre-loaded load (base64)...
glkote.js:1506 ### created canvas with scale 1 (device 1 / backstore 1)
quixe.js:179 ### done executing; path time = 8720 ms
glkote.js:1506 ### devicePixelRatio changed to 2
glkote.js:1506 ### changed canvas to scale 2 (device 2 / backstore 1)
quixe.js:179 ### done executing; path time = 20 ms
quixe.js:179 ### done executing; path time = 26 ms
quixe.js:179 ### done executing; path time = 10 ms
glkote.js:1506 ### devicePixelRatio changed to 1
glkote.js:1506 ### changed canvas to scale 1 (device 1 / backstore 1)
quixe.js:179 ### done executing; path time = 9 ms
glkote.js:1506 ### devicePixelRatio changed to 2
glkote.js:1506 ### changed canvas to scale 2 (device 2 / backstore 1)
quixe.js:179 ### done executing; path time = 14 ms
```

And Firefox:

`GiLoad: trying pre-loaded load (base64)... glkote.js:1506:5
### created canvas with scale 1 (device 1 / backstore 1) glkote.js:1506:5
### done executing; path time = 8596 ms quixe.js:179:9
### done executing; path time = 54 ms quixe.js:179:9
### done executing; path time = 19 ms quixe.js:179:9
### devicePixelRatio changed to 2 glkote.js:1506:5
### changed canvas to scale 2 (device 2 / backstore 1) glkote.js:1506:5
### done executing; path time = 10 ms quixe.js:179:9
### done executing; path time = 13 ms quixe.js:179:9
### done executing; path time = 9 ms quixe.js:179:9
### devicePixelRatio changed to 1 glkote.js:1506:5
### changed canvas to scale 1 (device 1 / backstore 1) glkote.js:1506:5
### done executing; path time = 32 ms quixe.js:179:9
### devicePixelRatio changed to 2 glkote.js:1506:5
### changed canvas to scale 2 (device 2 / backstore 1) glkote.js:1506:5
### done executing; path time = 18 ms quixe.js:179:9
### devicePixelRatio changed to 1 glkote.js:1506:5
### changed canvas to scale 1 (device 1 / backstore 1) glkote.js:1506:5
### done executing; path time = 10 ms quixe.js:179:9
### devicePixelRatio changed to 2`

Probably non-related stuff:
Chrome complains about missing favicon, Firefox about missing character encoding. Firefox has a problem with padding with wrong color when resizing:
<img width="842" alt="skarmavbild 2016-05-09 kl 09 12 37" src="https://cloud.githubusercontent.com/assets/5066755/15105987/5f9a52b8-15c6-11e6-8d89-3d7ab226b6c7.png">

**Comment by erkyrath** [comment]
It sounds like Safari just doesn't support the query I'm using to watch for devicePixelRatio changes. I'm going to not worry about this for now.

**Comment by erkyrath** [comment]
As for the other stuff: the padding with wrong color is annoying. That must be a discrepancy with the way color profiles are handled. I am very strongly inclined to not touch that with a twenty-foot pole.

**Comment by angstsmurf** [comment]
Yeah, I would guess images are color-adjusted according to profile while "drawn" colors (vector objects?) are not. I'm still pretty impressed that it works as well as it does on all three browsers.

**Comment by erkyrath** [comment]
Thanks for trying this. I've pushed Lectrote 1.0.1 with this fix.
