### ISSUE TITLE
On autorestore, the window isn't scrolled all the way down

### ISSUE THREAD

**Issue by erkyrath** [erkyrath/lectrote#57]
I think the margins or font gets set after glkote's "scroll to bottom" event. Maybe change how the window launches its code.

**Comment by erkyrath** [comment]
After a lot of debugging, I don't know what's going on here.

On the call to window_scroll_to_bottom (after autorestore), frameel.get(0).scrollHeight has a value. Sometime after glk_update finishes, but before the next glk event, frameel.get(0).scrollHeight gets larger (14 pixels larger in my test). I have not dug out the cause.

It's not the font, font size, or margins being set. It's not the DOM style metrics still being computed. It's not the invisible cursel or input field being added.

**Comment by curiousdannii** [comment]
Is this fixed with the latest changes?

**Comment by erkyrath** [comment]
Oh, good question.

(Quick check...)

Yep!
