### ISSUE TITLE
Changing margins does not issue a rearrange event

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/lectrote#71]
When you change the margins from the preferences panel, rearrange events are not sent to the VM, leaving odd results like this:

![An example of bad Lectrote margins](https://cloud.githubusercontent.com/assets/59074/19408260/5c2da52c-92fc-11e6-806f-a4b3c13fc69e.png)

The graphics window is set to take 50% of the width, and you can see from the sliver of black at the bottom that it is doing so. Changing the size of the window will issue a rearrange event and the game can sort itself out, but not all players will know they can do that.

**Comment by erkyrath** [comment]
You're right, there's a hole in the rearrange logic there.

Is this the cause of https://github.com/erkyrath/glkote/issues/12 ? (I haven't investigated that yet, but I can hope...)

**Comment by erkyrath** [comment]
This causes status-line layout problems in just about any Inform game with a right-hand status-line display, such as Advent.ulx. Shoulda noticed that months ago...

(Glkote puts a handler on the window size event, but CSS changes that affect #gameport also need to be detected.)

**Comment by erkyrath** [comment]
There's no DOM event for a size change on a div.

Polling is a possible answer, but I dislike it.

I see a frightening, but apparently reliable, method which involves making an invisible div and watching for scroll events... See https://github.com/marcj/css-element-queries/blob/master/src/ResizeSensor.js .

**Comment by curiousdannii** [comment]
I had thought you could just directly issue a Glk event from the preferences window. If you'd prefer to keep a level of separation, why not trigger the browser resize event? `$( window ).resize();`

**Comment by erkyrath** [comment]
That would work but I'd prefer to handle the general case.

**Comment by curiousdannii** [comment]
At another level of indirection you could wrap it all in an iframe, and change the iframe's size rather than #content.

Or you could probably use a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver). I have no idea how they work though.

**Comment by erkyrath** [comment]
Yes, there's a debounce timer in there. The arrange event isn't delivered until the browser size has settled down (0.2 seconds with no further change).

**Comment by erkyrath** [comment]
Glkote now has a resize sensor which covers this case.
