### ISSUE TITLE
Open dialog does not highlight .z5, .z8, etc

### ISSUE THREAD

**Issue by erkyrath** [erkyrath/lectrote#75]
Did I screw up the plist info? Maybe I can't have an array of extensions inside one entry.

**Comment by erkyrath** [comment]
Because you forgot to update the showOpenDialog call, genius.

**Comment by ffilipus** [comment]
Win64 1.1.8 release still doesn't show *.z8 files.

**Comment by erkyrath** [comment]
I am now including z5 and z8 in the dialog filters list. I don't know what else is necessary.

**Comment by erkyrath** [comment]
I tested this on Win7 and Win10. Windows has a file-type control on the right side of the file dialogue; you have to select "Z-code" in order to see .z5 and .z8 files. Seems weird to me, but I guess that's how Windows is supposed to work.

**Comment by curiousdannii** [comment]
The Windows convention would be for the default to be an "All games" type. Often there is also an "All files" type too, which doesn't filter at all.
