### ISSUE TITLE
Glulx BLORB fails to load correctly.

### ISSUE THREAD

**Issue by WillItWork** [erkyrath/lectrote#78]
This may be related to large gblorb issue (183 MB), or the margin render issue (git has this problem). Window opens, Loading icon clears, and… nothing.

This is mainly to include the output in case it would help debugging.

> MBPX7:MacOS devver$ ./Lectrote 
> 
> <--- Last few GCs --->
> 
>      149 ms: Scavenge 2.5 (9.0) -> 2.5 (9.0) MB, 0.7 / 0.0 ms [allocation failure].
>      172 ms: Scavenge 3.9 (11.0) -> 3.7 (13.0) MB, 0.4 / 0.0 ms [allocation failure].
>      220 ms: Scavenge 6.1 (14.0) -> 5.4 (14.0) MB, 1.3 / 0.0 ms [allocation failure].
>      288 ms: Scavenge 7.7 (15.0) -> 7.0 (19.0) MB, 1.3 / 0.0 ms [allocation failure].
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 0x25d554b13a49 <String[7]: file://>
>     1: load_named_game(aka load_named_game) [/Applications/Lectrote.app/Contents/Resources/app/apphooks.js:~11] [pc=0x306a068f32ef](this=0x34a3f1904399 <undefined>,arg=0x283a65015199 <an Object with map 0x3065be883711>)
>     2: /* anonymous */ [/Applications/Lectrote.app/Contents/Resources/app/apphooks.js:263] [pc=0x306a068e8c75](this=0xa4de708eed9 <an EventEmitter with map 0x3065be8421...

**Comment by curiousdannii** [comment]
Duplicate of https://github.com/erkyrath/lectrote/issues/76

**Comment by WillItWork** [comment]
Oh you already have the trace. Never mind, then. I suspected this was a dup of that.
