### ISSUE TITLE
Add zvm.css file

### ISSUE THREAD

**Issue by erkyrath** [erkyrath/lectrote#84]
See https://github.com/erkyrath/lectrote/issues/77#issuecomment-269713608

**Comment by erkyrath** [comment]
https://github.com/erkyrath/lectrote/blob/master/ifvms/zvm.css is my current version. I backed away from the reverse/normal distinction a bit, because I want the status line to look good in the common case.

I did make an attempt to keep Jigsaw playable, although it's not entirely successful.

**Comment by curiousdannii** [comment]
Looks good to me. I'll have a think about the line height issue.

**Comment by curiousdannii** [comment]
The lack of reverse styling in the upper window is meaning that quote boxes and menus are losing their formatting, Maybe the reverse colours could be made to be the current colours, with the normal colours being the same as the lower window?

**Comment by erkyrath** [comment]
I've added some intermediate colors.

**Comment by curiousdannii** [comment]
Line height and colour issues are addressed in #87
