### ISSUE TITLE
Transcripts have extraneous 0x00 bugs after commands

### ISSUE THREAD

**Issue by andrewschultz** [erkyrath/lectrote#89]
I don't know if this is general to all games, but the issue came across at intfic.com so I thought I'd report it. It's obviously pretty low priority.

Use case:

* open game "wade wars" http://ifdb.tads.org/viewgame?id=eipoymlzqmu5ps9h
* commands as attached (though it doesn't seem to matter)
[wadewars.txt](https://github.com/erkyrath/lectrote/files/862981/wadewars.txt)

Open in HXD or Notepad++ to see 00 bytes or [NUL] characters. There seem to be (120 - size of command in characters) such bytes.

**Comment by erkyrath** [comment]
(I assume you're talking about the file generated by SCRIPT ON.)

I don't see this on MacOS. Haven't tried on Windows.

I suppose it has to be a ZVM bug, unless you reproduce it on a Glulx game, so I will signal @curiousdannii.

**Comment by curiousdannii** [comment]
I was sure I had fixed this! I'll look into it.

**Comment by erkyrath** [comment]
Note to @andrewschultz: you demonstrated this with the latest release, right? (1.2.3 was just a week ago.)

**Comment by andrewschultz** [comment]
I had the wrong release. I looked back at previous releases and I can verify it's closed now. Sorry for the inconvenience here!
