### ISSUE TITLE
Hugo interpreter can't read it's own save files

### ISSUE THREAD

**Issue by brirush84** [erkyrath/lectrote#98]
After compiling Lectrote, when running a hex file (such as czk.hex), if you use SAVE and then later RESTORE, you get the message:

"Save file created by different version.
Unable to restore."

**Comment by erkyrath** [comment]
This is handled by the hugo-emglken code, which I am not familiar with. Kicking it over the fence: https://github.com/curiousdannii/emglken/issues/3

**Comment by brirush84** [comment]
Thanks!

On Sep 30, 2017 9:59 AM, "Andrew Plotkin" <notifications@github.com> wrote:

This is handled by the hugo-emglken code, which I am not familiar with.
Kicking it over the fence: curiousdannii/emglken#3
<https://github.com/curiousdannii/emglken/issues/3>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/erkyrath/lectrote/issues/98#issuecomment-333321517>,
or mute
the thread
